{{ if .Values.alerts.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: "{{ .Release.Name }}"
  labels:
    control-plane: controller-manager
    {{- include "fqdn-policy.labels" . | nindent 4 }}
spec:
  groups:
    - name: "{{ .Release.Name }}-alerts"
      rules:
        - alert: Reconciles failing
          expr: increase(controller_runtime_reconcile_total{job="nais-system/{{ .Release.Name }}", result="error"}[2m]) > 0
          for: 5m
          labels:
            namespace: nais-system
            severity: warning
          annotations:
            consequence: Network policy not updated.
            action: "Check logs in `{{"{{ $labels.namespace }}`/`{{ $labels.pod }}"}}`"
            dashboard_url: "https://monitoring.nais.io/d/fefi4qz2462v4f/fqdn-policy-controller?var-tenant={{.Values.fasit.tenant.name }}&var-cluster={{ .Values.fasit.env.name }}"
{{- end }}
