containerSecurityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false

image:
  repository: "europe-north1-docker.pkg.dev/nais-io/nais/images/fqdn-policy"
  tag: "0.3"

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

replicas: 1

resources:
  limits:
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 20Mi

deploymentAnnotations: {}
