name: Build and deploy
on:
  push:
    paths-ignore:
      - "*.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FEATURE_NAME: "fqdn-policy"
  FEATURE_REPOSITORY: oci://europe-north1-docker.pkg.dev/nais-io/nais/feature

permissions:
  contents: "read"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # ratchet:actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - run: mise run check
      - run: mise run test

  build_and_push:
    if: github.ref == 'refs/heads/main'
    needs:
      - tests
    permissions:
      id-token: "write"
      packages: "write"
    name: build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # ratchet:jdx/mise-action@v4
      - id: go_version
        run: echo "go_version=$(mise current go)" >> $GITHUB_OUTPUT

      - uses: nais/platform-build-push-sign@a16d89d06262f12e3468a20b9cc70f5317290bab # ratchet:nais/platform-build-push-sign@main
        id: build_push_sign
        with:
          name: ${{ env.FEATURE_NAME }}
          google_service_account: gh-${{ env.FEATURE_NAME }}
          workload_identity_provider: ${{ secrets.NAIS_IO_WORKLOAD_IDENTITY_PROVIDER }}
          push: true
          push_ghcr: true
          build_args: |
            GO_VERSION=${{ steps.go_version.outputs.go_version }}

      - name: Push Chart
        run: |-
          helm push ${{ env.NAME }}*.tgz ${{ env.FEATURE_REPOSITORY }}

      - name: Package chart
        id: package_chart
        env:
          CHART_PATH: ./charts
        run: |
          base_version="$(yq '.version' < "${{ env.CHART_PATH }}/Chart.yaml")"
          chart_version="${base_version}-${{ steps.build_push_sign.outputs.version }}"

          yq eval \
            '.version="'"$chart_version"'"' \
            "${{ env.CHART_PATH }}/Chart.yaml" --inplace
          yq eval \
            '.image.tag="${{ steps.build_push_sign.outputs.version }}"' \
            "${{ env.CHART_PATH }}/values.yaml" --inplace

          # helm dependency update "${{ env.CHART_PATH }}"
          helm package "${{ env.CHART_PATH }}" --destination .

          name=$(yq '.name' < "${{ env.CHART_PATH }}/Chart.yaml")
          echo "name=$name" >> $GITHUB_OUTPUT
          echo "version=$chart_version" >> $GITHUB_OUTPUT
          echo "archive=$name-$chart_version.tgz" >> $GITHUB_OUTPUT
      - name: Push Chart
        run: |-
          chart="${{ steps.package_chart.outputs.archive }}"
          echo "Pushing: $chart"
          helm push "$chart" ${{ env.FEATURE_REPOSITORY }}
    outputs:
      version: ${{ steps.build_push_sign.outputs.version }}

  rollout:
    needs:
      - build_and_push
    runs-on: fasit-deploy
    permissions:
      id-token: write
    steps:
      - uses: nais/fasit-deploy@8727ed1c7a5a465e837873e6016a9a692a6b874a # ratchet:nais/fasit-deploy@v2
        with:
          chart: ${{ env.FEATURE_REPOSITORY }}/${{ env.NAME }}
          version: ${{ needs.build_and_push.outputs.version }}
